/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "secondary-container": "#00a2e6",
          "secondary-fixed-dim": "#89ceff",
          "on-primary": "#1000a9",
          "primary-fixed": "#e1e0ff",
          "on-primary-fixed": "#07006c",
          "surface-container-lowest": "#060e20",
          "outline": "#908fa0",
          "on-error": "#690005",
          "inverse-on-surface": "#283044",
          "secondary": "#89ceff",
          "tertiary-fixed-dim": "#ffb783",
          "primary-container": "#8083ff",
          "on-surface": "#dae2fd",
          "on-primary-container": "#0d0096",
          "background": "#0b1326",
          "error-container": "#93000a",
          "surface-dim": "#0b1326",
          "surface-variant": "#2d3449",
          "inverse-surface": "#dae2fd",
          "surface-tint": "#c0c1ff",
          "on-secondary-container": "#00344e",
          "surface-container-high": "#222a3d",
          "on-error-container": "#ffdad6",
          "on-background": "#dae2fd",
          "surface-container-low": "#131b2e",
          "on-tertiary": "#4f2500",
          "on-tertiary-fixed-variant": "#703700",
          "on-tertiary-container": "#452000",
          "surface-container": "#171f33",
          "on-secondary-fixed": "#001e2f",
          "on-surface-variant": "#c7c4d7",
          "tertiary": "#ffb783",
          "tertiary-container": "#d97721",
          "on-primary-fixed-variant": "#2f2ebe",
          "inverse-primary": "#494bd6",
          "on-secondary": "#00344d",
          "outline-variant": "#464554",
          "surface": "#0b1326",
          "primary": "#c0c1ff",
          "surface-container-highest": "#2d3449",
          "error": "#ffb4ab",
          "primary-fixed-dim": "#c0c1ff",
          "surface-bright": "#31394d",
          "tertiary-fixed": "#ffdcc5",
          "on-secondary-fixed-variant": "#004c6e",
          "on-tertiary-fixed": "#301400",
          "secondary-fixed": "#c9e6ff"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "xs": "4px",
          "base": "4px",
          "gutter": "24px",
          "2xl": "64px",
          "container-max": "1280px",
          "sm": "8px",
          "margin-mobile": "16px",
          "xl": "40px",
          "lg": "24px",
          "md": "16px"
      },
      "fontFamily": {
          "headline-lg": ["Geist", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "code-md": ["JetBrains Mono", "monospace"],
          "body-sm": ["Inter", "sans-serif"],
          "display-md": ["Geist", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "display-lg": ["Geist", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-md": ["Geist", "sans-serif"],
          "headline-lg-mobile": ["Geist", "sans-serif"]
      },
      "fontSize": {
          "headline-lg": ["30px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "code-md": ["14px", {"lineHeight": "1.6", "fontWeight": "450"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "display-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
          "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
